

import "./globals.css";
import 'bootstrap/dist/css/bootstrap.rtl.css'
import localFont from 'next/font/local'
const myFont = localFont({ src: '../public/WebFonts/IRANSans-web.woff2' })
export const metadata = {
  title: "Gamers",
  description: "Generated by create next app",
};



//👇 Configure our font object

export default function RootLayout({ children }) {

  return (
    <html  >
      <head >
        <script
          // you might need to get a newer version
          src="https://kit.fontawesome.com/fbadad80a0.js"
          crossOrigin="anonymous"
        ></script>
      </head>

      <body className={myFont.className}>{children}</body>
     
    </html>
  );
}
