// import { Inter } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.rtl.min.css'
import Header from "@/components/Header";
import Head from "next/head";
// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html>
      <head>
        <script
          // you might need to get a newer version
          src="https://kit.fontawesome.com/fbadad80a0.js"
          crossOrigin="anonymous"
        ></script>
      </head>

      <body lang="ar">{children}</body>
    </html>
  );
}
