
import Footer from "@/components/Footer";
import "./globals.css";

import 'bootstrap/dist/css/bootstrap.rtl.min.css'
import { Open_Sans } from 'next/font/google'
export const metadata = {
  title: "Gamers",
  description: "Generated by create next app",
};


//👇 Configure our font object
const openSans = Open_Sans({
  subsets: ['latin'],
  display: 'swap',
})
export default function RootLayout({ children }) {
  return (
    <html className={openSans.className}>
      <head>
        <script
          // you might need to get a newer version
          src="https://kit.fontawesome.com/fbadad80a0.js"
          crossOrigin="anonymous"
        ></script>
      </head>

      <body lang="en">{children}</body>
      {/* <Footer></Footer> */}
    </html>
  );
}
